import PrimeGPF

-- All theorem declarations, including explicitly conditional ones.
#print axioms PrimeGPF.gpf_ne_two_of_mod_four
#print axioms PrimeGPF.square_output_ne_two
#print axioms PrimeGPF.inverse_witness
#print axioms PrimeGPF.proof_5_1
#print axioms PrimeGPF.proof_5_6
#print axioms PrimeGPF.collision_divisor
#print axioms PrimeGPF.additive_residue_unique
#print axioms PrimeGPF.collision_residue_exists
#print axioms PrimeGPF.proof_9_4
#print axioms PrimeGPF.proof_9_5
#print axioms PrimeGPF.collision_two_polynomials
#print axioms PrimeGPF.proof_9_7
#print axioms PrimeGPF.proof_9_2
#print axioms PrimeGPF.refutation_order_dependency
#print axioms PrimeGPF.proof_order_dependency
#print axioms PrimeGPF.proof_8_3_from_external
#print axioms PrimeGPF.proof_3_5_from_8_1
#print axioms PrimeGPF.proof_8_2_from_5_2
#print axioms PrimeGPF.proof_8_4_from_bounds
#print axioms PrimeGPF.exponential_growth
#print axioms PrimeGPF.proof_8_5_from_bounds
#print axioms PrimeGPF.proof_9_3_from_8_3
#print axioms PrimeGPF.proof_9_8_from_9_6_9_7
#print axioms PrimeGPF.proof_8_1_from_8_3
#print axioms PrimeGPF.proof_8_3_from_zsigmondy
#print axioms PrimeGPF.proof_8_4_from_zsigmondy
#print axioms PrimeGPF.proof_8_5_from_zsigmondy
#print axioms PrimeGPF.proof_9_3_from_zsigmondy
#print axioms PrimeGPF.scan_le
#print axioms PrimeGPF.prime_le_scan
#print axioms PrimeGPF.scan_sound
#print axioms PrimeGPF.gpf_spec
#print axioms PrimeGPF.gpf_le
#print axioms PrimeGPF.gpf_eq_of_spec
#print axioms PrimeGPF.gpf_eq_iff
#print axioms PrimeGPF.gpf_prime_self
#print axioms PrimeGPF.gpf_eq_self_iff
#print axioms PrimeGPF.smooth_of_gpf
#print axioms PrimeGPF.gpf_fiber
#print axioms PrimeGPF.power_of_prime_support
#print axioms PrimeGPF.gpf_prime_power
#print axioms PrimeGPF.gpf_eq_two_iff
#print axioms PrimeGPF.kernel_gt_one
#print axioms PrimeGPF.output_spec
#print axioms PrimeGPF.oddCofactor_identity
#print axioms PrimeGPF.oddCofactor_odd
#print axioms PrimeGPF.oddCofactor_pos
#print axioms PrimeGPF.oddCofactor_gt_one
#print axioms PrimeGPF.gpf_ne_two_of_odd_divisor
#print axioms PrimeGPF.odd_base_odd_exp_ne_two
#print axioms PrimeGPF.exp_ne_two_direct
#print axioms PrimeGPF.proof_8_1
#print axioms PrimeGPF.proof_3_5
#print axioms PrimeGPF.orbit_repeat
#print axioms PrimeGPF.eventuallyPeriodic_of_repeat
#print axioms PrimeGPF.proof_7_5
#print axioms PrimeGPF.proof_5_3_from_5_2
#print axioms PrimeGPF.increasing_orbit
#print axioms PrimeGPF.proof_3_1
#print axioms PrimeGPF.add_comm
#print axioms PrimeGPF.mul_comm
#print axioms PrimeGPF.proof_3_2
#print axioms PrimeGPF.proof_3_3
#print axioms PrimeGPF.mul_ne_left
#print axioms PrimeGPF.mul_ne_right
#print axioms PrimeGPF.add_not_idempotent
#print axioms PrimeGPF.exp_ne_left
#print axioms PrimeGPF.proof_3_4
#print axioms PrimeGPF.odd_add_closed
#print axioms PrimeGPF.odd_mul_not_closed
#print axioms PrimeGPF.proof_3_6
#print axioms PrimeGPF.proof_3_7
#print axioms PrimeGPF.proof_3_8
#print axioms PrimeGPF.proof_4_1
#print axioms PrimeGPF.proof_4_2
#print axioms PrimeGPF.mul_two_iff
#print axioms PrimeGPF.kernel_congruences
#print axioms PrimeGPF.fixed_dvd
#print axioms PrimeGPF.fixed_criterion
#print axioms PrimeGPF.fixed_set_subset
#print axioms PrimeGPF.fixed_divisors_finite
#print axioms PrimeGPF.proof_7_1
#print axioms PrimeGPF.proof_7_2
#print axioms PrimeGPF.proof_7_3
#print axioms PrimeGPF.proof_7_4
#print axioms PrimeGPF.proof_9_1
#print axioms PrimeGPF.counterexample_5_5
#print axioms PrimeGPF.refutation_5_5
#print axioms PrimeGPF.cast_eq_iff_mod
#print axioms PrimeGPF.cast_zero_iff_dvd
#print axioms PrimeGPF.cast_pow_one_iff
#print axioms PrimeGPF.exactOrder_iff_orderOf
#print axioms PrimeGPF.primitiveDivisor_iff_orderOf
#print axioms PrimeGPF.primitive_order_dvd
#print axioms PrimeGPF.mod_eq_one_of_dvd_pred
#print axioms PrimeGPF.dyadic_order
#print axioms PrimeGPF.proof_5_2
#print axioms PrimeGPF.proof_5_3
#print axioms PrimeGPF.proof_8_2
#print axioms PrimeGPF.proof_5_5_corrected
#print axioms PrimeGPF.proof_5_5
#print axioms PrimeGPF.affine_residue
#print axioms PrimeGPF.multiplicative_progression
#print axioms PrimeGPF.additive_progression
#print axioms PrimeGPF.additive_degenerate_progression
#print axioms PrimeGPF.proof_6_1_from_PNT_AP
#print axioms PrimeGPF.finite_square_iff
#print axioms PrimeGPF.quadraticCharacter_eq
#print axioms PrimeGPF.proof_5_4
#print axioms PrimeGPF.collision_discriminant
#print axioms PrimeGPF.square_five_residues
#print axioms PrimeGPF.proof_9_6
#print axioms PrimeGPF.proof_9_8
#print axioms PrimeGPF.odd_gpf_three_iff
#print axioms PrimeGPF.exponent_three_ge_two
#print axioms PrimeGPF.exponent_two_ge_three
#print axioms PrimeGPF.add_two_small
#print axioms PrimeGPF.mul_two_odd_opposite
#print axioms PrimeGPF.odd_add_three
#print axioms PrimeGPF.add_three_mod_six
#print axioms PrimeGPF.two_mul_three
#print axioms PrimeGPF.proof_4_3
#print axioms PrimeGPF.prime_representative
#print axioms PrimeGPF.additive_section_unbounded
#print axioms PrimeGPF.multiplicative_section_unbounded
#print axioms PrimeGPF.exponential_base_unbounded
#print axioms PrimeGPF.proof_6_4

#print axioms PrimeGPF.factorization_le_natLog
#print axioms PrimeGPF.factorization_le_boxExponent
#print axioms PrimeGPF.smoothCount_le_smoothBoxBound

#print axioms PrimeGPF.smoothBox_factor_real_le
#print axioms PrimeGPF.smoothBoxBound_real_le
#print axioms PrimeGPF.proof_smoothPolylog

#print axioms PrimeGPF.fiberCofactor_spec
#print axioms PrimeGPF.add_kernel_le_sq
#print axioms PrimeGPF.mul_kernel_le_sq
#print axioms PrimeGPF.fiberCofactor_add_le_sq
#print axioms PrimeGPF.fiberCofactor_mul_le_sq
#print axioms PrimeGPF.fiberCount_add_le_smoothCount_sq
#print axioms PrimeGPF.fiberCount_mul_le_smoothCount_sq
#print axioms PrimeGPF.proof_uniformPolylogFibers
#print axioms PrimeGPF.proof_6_2


-- Counting and asymptotic-density machinery for theorem 6.3.
#print axioms PrimeGPF.add_kernel_le_succ_sq
#print axioms PrimeGPF.mul_kernel_le_succ_sq
#print axioms PrimeGPF.pairCount_add_le
#print axioms PrimeGPF.pairCount_mul_le
#print axioms PrimeGPF.apCount_le_primeCount
#print axioms PrimeGPF.primeCount_eq_primeCounting
#print axioms PrimeGPF.APAsymptotic.eventually_half_mainTerm_le
#print axioms PrimeGPF.PrimeAPInput.eventually_AP3_lower_le_primeCount
#print axioms PrimeGPF.isLittleO_log_pow_id_atTop
#print axioms PrimeGPF.tendsto_log_pow_div_natCast_atTop
#print axioms PrimeGPF.PrimeAPInput.tendsto_log_pow_div_primeCount
#print axioms PrimeGPF.smoothCount_succ_sq_polylog
#print axioms PrimeGPF.PrimeAPInput.tendsto_smoothCount_succ_sq_div_primeCount
#print axioms PrimeGPF.PrimeAPInput.pairZero_of_pairCount_le
#print axioms PrimeGPF.PrimeAPInput.pairZero_add
#print axioms PrimeGPF.PrimeAPInput.pairZero_mul
#print axioms PrimeGPF.APAsymptotic.tendsto_log_pow_div_apCount
#print axioms PrimeGPF.relativeZero_of_polylog_AP
#print axioms PrimeGPF.proof_6_3_from_PNT_AP

-- These types expose remaining hypotheses.
#check PrimeGPF.proof_8_3_from_zsigmondy
#check PrimeGPF.proof_6_1_from_PNT_AP
#check PrimeGPF.proof_6_3_from_PNT_AP
#print axioms PrimeGPF.oddCofactor_cast
#print axioms PrimeGPF.oddCofactor_ge_exp
#print axioms PrimeGPF.oddCofactor_gt_exp
#print axioms PrimeGPF.oddCofactor_odd_all
#print axioms PrimeGPF.oddCofactor_step_ge_two
#print axioms PrimeGPF.prime_divisor_cofactor
#print axioms PrimeGPF.proof_8_3
#print axioms PrimeGPF.proof_8_4
#print axioms PrimeGPF.proof_8_5
#print axioms PrimeGPF.proof_9_3
#print axioms PrimeGPF.proof_zsigmondy_dependency
