name = "prime_gpf"
version = "0.1.0"
defaultTargets = ["PrimeGPF"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"
rev = "ddac5ceafd30932b0c7e81d710e429cf7d4df6d2"

[[lean_lib]]
name = "PrimeGPF"
