import PrimeGPF.Extension2Primitive

/-!
# Extension 2: logarithmic bound for nonprimitive families

The report only needs that the two exceptional perfect-power families contain
`O_a(log X)` possible exponents.  These lemmas give the exact natural-log
bounds from which that statement follows.
-/
namespace PrimeGPF

/-- If a kernel in the first exceptional family is generated by an input
`q ≤ X`, its exponent is bounded by the base-two logarithm of `a*X+1`. -/
theorem extension2_two_power_exponent_le_log
    {a q X g : ℕ} (hqX : q ≤ X)
    (hpow : a * q + 1 = 2 ^ g) :
    g ≤ Nat.log 2 (a * X + 1) := by
  have hle : 2 ^ g ≤ a * X + 1 := by
    rw [← hpow]
    exact Nat.add_le_add_right (Nat.mul_le_mul_left a hqX) 1
  exact Nat.le_log_of_pow_le (by decide : 1 < (2 : ℕ)) hle

/-- The corresponding exponent bound for the second exceptional family. -/
theorem extension2_anchor_succ_power_exponent_le_log
    {a q X g : ℕ} (ha : Nat.Prime a) (hqX : q ≤ X)
    (hpow : a * q + 1 = (a + 1) ^ g) :
    g ≤ Nat.log (a + 1) (a * X + 1) := by
  have hle : (a + 1) ^ g ≤ a * X + 1 := by
    rw [← hpow]
    exact Nat.add_le_add_right (Nat.mul_le_mul_left a hqX) 1
  exact Nat.le_log_of_pow_le (by omega) hle

/-- Unified logarithmic exponent bound for a nonprimitive kernel `u^g` with
`q>a`, using the classification into the two exceptional families. -/
theorem extension2_nonprimitive_exponent_bound
    {a q X u g : ℕ} (ha : Nat.Prime a) (hq : Nat.Prime q)
    (haq : a < q) (hqX : q ≤ X) (hg : 2 ≤ g)
    (hpow : u ^ g = a * q + 1) :
    (u = 2 ∧ g ≤ Nat.log 2 (a * X + 1)) ∨
    (u = a + 1 ∧ g ≤ Nat.log (a + 1) (a * X + 1)) := by
  rcases extension2_nonprimitive_power_base ha hq haq hg hpow with hu | hu
  · left
    refine ⟨hu, ?_⟩
    apply extension2_two_power_exponent_le_log hqX
    rw [← hpow, hu]
  · right
    refine ⟨hu, ?_⟩
    apply extension2_anchor_succ_power_exponent_le_log ha hqX
    rw [← hpow, hu]

end PrimeGPF
